### ISSUE TITLE
Large amount of MySQL connections being opened and not closed (sleep)

### ISSUE THREAD

**Issue by booni3** [laravel/telescope#818]
- Telescope Version: 2.1.4
- Laravel Version: 6.13.1
- PHP Version: 7.3
- Database Driver & Version: MySQL 8.0.11

### Description:
Telescope is opening a huge amount of connections on every request whether or not a query is being ran. I first realised this was happening when my RDS instance kept throwing exceptions due to no available connections. Running 10 queue jobs without any SQL queries inside will easily open 60+ connections.

### Steps To Reproduce:
- Install fresh copy of Laravel
- Install vapor-core, telescope & laravel/ui with Vue auth scaffolding.
- Add my email to the telescope gate. Leave everything else default.
- Create a new job with a `sleep(10)` as the only operation called.
- Deploy via Vapor with RDS micro instance.
- Dispatch 10 instances of this job.

Example MySQL `SHOW PROCESSLIST`  output
![image](https://user-images.githubusercontent.com/20134485/73453062-216f7f80-4363-11ea-9589-27e70e2d2703.png)

- To add, this behaviour seems to be present no matter what I return from the telescope filter (return false) and even seemed to happen if the service provider was conditionally registered to local only.

**Comment by barryvdh** [comment]
Do you have a separate connection for Telescope? If so, each job would actually open 2 connections, right?
With Vapor, dispatching 10 jobs at the same time would lead to 10 different containers that open connections. So 10 jobs with 2 connections are 20 connections, that are kept alive until the Lambda container dies (after half a hour or so). Not sure why you would get 60 though..

**Comment by booni3** [comment]
My setup is default to what telescope ships with. How would I check to see if it is on a separate connection?

I just checked again (with this project not being invoked for about 24 hours) and it seems that there mya have been some other connections at play when I first reported.

Starting my 10 jobs actually creates 26 sleep connections. At this point I am not logged in and the job consists of nothing but a `sleep(10)` in the handle. I can see why 10 connections would be open to telescope but why would any others be open if we are not hitting any databases?

Additionally should the telescope connections not be closed?

I have since updated my RDS configuration with a `wait_timeout` of 60 seconds, so all these sleep connections are closed after 60 seconds. However,  it does not really help. When running jobs which take 20 - 30 seconds each you can easily send enough to the queue to use up all the connections of the RDS instance (especially with the power of unlimited concurrent execution provided by serverless!)

Do you want me to provide any further information on this? I would love to be able to use Telescope with vapor.

**Comment by themsaid** [comment]
Can you replicate the behaviour on your local machine?

**Comment by booni3** [comment]
I have not been able to no. I also use telescope on a traditional server setup and have not seen this issue before. I run a lot of queue workers in most of my apps so think it would have been apparent quite quickly.

**Comment by themsaid** [comment]
After handling a job, Vapor closes any open database connections. I haven't been able to replicate what you're describing in this issue. As soon as a job is done, I see the connection gets closed.

**Comment by booni3** [comment]
Hmm... very strange as I cant really see anything on the application side that I have modified from the default Larval setup. The RDS setup is also completely default although it does have another application connected to it also. My vapor config is updated slightly:

```yaml
id: 6683
name: vapor-test
separate-vendor: true
    staging:
        memory: 1024
        cli-memory: 512
        runtime: php-7.3
        database: test-db
        build:
            - 'composer install'
            - 'php artisan event:cache'
            - 'npm ci && npm run dev && rm -rf node_modules'
        deploy:
          - 'php artisan migrate --force'
        queue-memory: 512
        queue-timeout: 60
        queue-concurrency: 50
```

The only other thing I can think of is spinning up a fresh RDS instance. Can you think of anything else?
